name: Test Windows Scaffolding Issue

on:
  push:
    branches: [main]

jobs:
  test-windows-scaffolding:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install holochain_scaffolding_cli
        run: cargo install holochain_scaffolding_cli --version 0.500.0-dev.1

      - name: Test scaffolding commands
        run: |
          chdir test-app
          hc-scaffold zome posts --integrity dnas\forum\zomes\integrity\ --coordinator dnas\forum\zomes\coordinator\
          tree /f
        shell: pwsh

      - name: Upload error logs if failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: test-reproduction/test-app/
          if-no-files-found: warn
